src/asciidoc/docs/_includes/voteCounterReact.js

Update voteCounterReact.js tag:callDataHandler[]

---

src/asciidoc/docs/_includes/customVCCReact.js
src/asciidoc/docs/_includes/customVCCVanilla.js
src/asciidoc/docs/_includes/vcc-blueprint-babelrc.json
src/asciidoc/docs/_includes/vcc-blueprint-settings.json
src/asciidoc/docs/_includes/vcc-blueprint-styles.css
src/asciidoc/docs/blueprints/blueprints.adoc
src/asciidoc/docs/blueprints/customVCC.adoc
src/asciidoc/reference/packages/withkojiCustomVccSdk.adoc
src/nav.json

Cat Breed Custom VCC blueprint

Add Custom VCC Blueprint

---

src/asciidoc/reference/packages/overview.adoc
src/asciidoc/reference/packages/withkojiDatabase.adoc
src/asciidoc/reference/packages/withkojiUserDefaults.adoc
src/nav.json

Hi @sthielen , here is a draft of the reference docs for your new package. Can you please review it and let me know if changes are needed?

User Defaults package reference

---

package-lock.json
src/asciidoc/docs/blueprints/magazineCover.adoc
src/asciidoc/docs/publish/richPreview.adoc
src/asciidoc/reference/packages/withkojiVCC.adoc

@sthielen please review the changes to onSetValue and let me know if changes are required. Thanks!

Add skipUpdate to onSetValue, minor updates to code block tabs

---

gatsby-config.js
src/layouts/index.js
src/styles/adoc-koji.css
src/styles/dark-code.css
src/templates/Asciidoc/components/Content.js
src/templates/Asciidoc/utils/copy-code.js

- Update font awesome version.
- Set global 'icons' to 'font' for asciidoc.
- Update asciidoc style to improve font icon for code callouts and admonition icons

Font Awesome Icons + Style changes

---

src/asciidoc/docs/_includes/startGuide2.svelte
src/asciidoc/docs/_includes/startGuide2Angular.ts
src/asciidoc/docs/_includes/startGuide2React.js
src/asciidoc/docs/_includes/startGuide2Vanilla.js
src/asciidoc/docs/_includes/starterExamples.adoc
src/asciidoc/docs/customizations/remixStates.adoc
src/asciidoc/docs/getting-started/startGuide1.adoc
src/asciidoc/docs/getting-started/startGuide2.adoc
src/asciidoc/docs/publish/richPreview.adoc
src/nav.json

@arist0tl3 the second guide is ready for your review. Note that the Angular version is not working all the way (the template loading section is failing). Please let me know if these changes look ready to publish. Thanks!

Starter guide 2, add frameworks, remove states

---

src/asciidoc/docs/about/developerUpdates.adoc
src/asciidoc/reference/packages/withkojiIAP.adoc

@sthielen can you please review these updates to the in-app purchase docs and the changelog for dynamic receipts? Please let me know if I missed or misunderstood anything and what changes are required. Thanks!

Oct 12 updates and IAP updates

---

src/asciidoc/reference/packages/withkojiCustomVccSdk.adoc
src/asciidoc/reference/packages/withkojiIAP.adoc

Hi @sthielen, while updating the package readme files, I found a few misc updates that affect the docs. Can you please review and let me know if changes are needed?

Remove showModal, add receiptId to purchase handler

---

src/asciidoc/docs/about/developerUpdates.adoc
src/asciidoc/docs/blueprints/customVCC.adoc
src/asciidoc/docs/customizations/buildCustomVcc.adoc
src/asciidoc/docs/publish/customDomains.adoc
src/asciidoc/docs/publish/plugins.adoc
src/nav.json

Custom domains

---

CONTRIBUTING.md
src/asciidoc/docs/_includes/tip-discord-server.adoc
src/asciidoc/docs/getting-started/developer.adoc
src/asciidoc/docs/getting-started/developerUpdates.adoc
src/components/AppBar.js

@arist0tl3 updating the Discord links to the new server. Can you do a quick sanity check before I merge this?

Update Discord links

---

src/asciidoc/tutorials/getting-started/your-first-remix.adoc

The current instructions are out of date. Bouncy Blast is nowhere to be found on the linked page; it's actually under 'Engage Your Audiences'.

Correct instructions to help readers find template

---

src/styles/adoc-koji.css
src/templates/Asciidoc/components/Content.js

- DC-543 Admonition icons or colors
- DC-595 Section descriptions in Quick Start Tutorial are not capitalized.

DC-543 Admonition colors + DC-595 init-cap

---

src/asciidoc/docs/publish/richPreview.adoc

DC-600 Add screenshot optimization recommendations for open graph

DC-600 Image optimization

---

src/asciidoc/reference/deprecated/deprecated.adoc
src/asciidoc/reference/packages/overview.adoc
src/nav.json

Move deprecated packages to subpage for better nav

---

src/asciidoc/docs/develop/portExistingCode.adoc

Porting existing code

---

gatsby-config.js
src/asciidoc/docs/guides-general/customDomains.adoc

Rachel added the attribute and updated one topic. Need the attribute to start adding the macros in other topics now.
Please do not delete the branch when merging.
Thanks!

Enable macros site-wide and test one page

---

.editorconfig
.prettierrc
src/templates/CorePackage/index.js

(also adds an editorconfig file)

Fixes DC-626

---

src/asciidoc/docs/develop/addService.adoc

Adding a service

---

src/asciidoc/docs/_includes/steps-dev-portal.adoc
src/asciidoc/docs/distribute/app-store.adoc
src/nav.json

First draft.
Waiting for Luis to confirm that he's fine with the last step because he seems to be the only one handling the App Store additions.
Added Sean as a reviewer because I made some guesses that also need confirmation.

DC-628 New: App Store

---

src/asciidoc/docs/develop/local-development/localDevelopment.adoc
src/asciidoc/docs/getting-started/developer.adoc
src/asciidoc/docs/getting-started/first-project/quickStart.adoc
src/asciidoc/docs/guides-general/game-iap/intro.adoc
src/asciidoc/docs/guides-general/game-tutorial/intro.adoc
src/templates/Asciidoc/components/Content.js

Added classes to implement cards.
Updated quickstart.adoc (tutorial intro) with the new classes.

DC-587 Implement list style for landing page

---

src/asciidoc/archived/blueprints/voteCounter.adoc
src/asciidoc/docs/develop/addService.adoc
src/asciidoc/docs/develop/editor.adoc
src/asciidoc/docs/develop/local-development/publishLocal.adoc
src/asciidoc/docs/develop/local-development/workLocally.adoc
src/asciidoc/docs/develop/testingApps.adoc
src/asciidoc/docs/getting-started/developer-updates/2020Updates.adoc
src/asciidoc/docs/guides-general/game-iap/start-purchase.adoc
src/asciidoc/docs/guides-general/game-iap/updating-game.adoc
src/asciidoc/docs/guides-general/game-tutorial/remix.adoc
src/asciidoc/docs/guides-general/game-tutorial/thumbnail-preview.adoc
src/asciidoc/docs/platform-features/database.adoc
src/nav.json

Testing and debugging apps

---

src/asciidoc/docs/_includes/images-annotated.adoc
src/asciidoc/docs/_includes/steps-codeeditor.adoc
src/asciidoc/docs/develop/editor.adoc
src/asciidoc/docs/develop/testingApps.adoc
src/asciidoc/docs/guides-general/customDomains.adoc
src/asciidoc/docs/guides-general/plugins.adoc

Terminology updates for misc pages

---

src/asciidoc/docs/_includes/tutorialEditorNote.adoc
src/asciidoc/docs/guides-general/game-iap/game-iap-customization.adoc
src/asciidoc/docs/guides-general/game-iap/intro.adoc
src/asciidoc/docs/guides-general/game-iap/payment-menu.adoc
src/asciidoc/docs/guides-general/game-iap/setting-up-koji-json.adoc
src/asciidoc/docs/guides-general/game-iap/updating-game.adoc
src/asciidoc/docs/guides-general/game-tutorial/creating-game-objects.adoc
src/asciidoc/docs/guides-general/game-tutorial/finishing-up.adoc
src/asciidoc/docs/guides-general/game-tutorial/game-customization.adoc
src/asciidoc/docs/guides-general/game-tutorial/intro.adoc
src/asciidoc/docs/guides-general/game-tutorial/managing-difficulty.adoc
src/asciidoc/docs/guides-general/game-tutorial/scoring-and-losing.adoc
src/asciidoc/docs/guides-general/game-tutorial/setting-up-assets.adoc
src/asciidoc/docs/guides-general/game-tutorial/thumbnail-preview.adoc
src/nav.json

Terminology updates for game tutorials

---

src/asciidoc/docs/guides-general/capture-user-input.adoc
src/asciidoc/docs/guides-general/enable-file-uploads.adoc
src/nav.json

There are two or three areas that I don't think I covered well:
* the more obscure options for images
* watermarking for videos
* uploading content generated within the app
I created a new Jira to create an "advanced example" (https://withkoji.atlassian.net/browse/DC-646) to play with those more, then I'll update this topic with what I find out then.

DC-638 New: Uploading files

---

src/asciidoc/docs/_includes/images-annotated.adoc
src/asciidoc/docs/develop/app-dev-process.adoc
src/templates/Asciidoc/components/Content.js

Styling changes only. No need for a tech review.

DC-652 Update the styling of callouts

---

src/asciidoc/docs/_includes/starterScaffolds.adoc
src/asciidoc/docs/_includes/steps-app-store.adoc
src/asciidoc/docs/develop/local-development/useGit.adoc
src/asciidoc/docs/develop/portExistingCode.adoc
src/asciidoc/docs/guides-general/game-iap/intro.adoc
src/asciidoc/docs/guides-general/game-tutorial/setting-up-assets.adoc
src/asciidoc/docs/platform-features/capture-user-input.adoc

No tech review required. All URLs were copied from the App Store.

DC-651 Update titles of scaffolds mentioned in the docs
